### ISSUE TITLE
Missing `; charset=UTF-8` from HTML multipart field Content-Type header

### ISSUE THREAD

**Issue by mqudsi** [lukencode/FluentEmail#110]
_Presuming this repo/project is maintained. Attempted to identify quickly the code responsible for this but it seems I am one level of abstraction too deep._

The multipart message generated by FluentEmail correctly sets the encoding for the `text/plain` portion of the email but fails to set a charset for the `text/html` payload. While some webmail systems (e.g. Gmail) default to UTF-8 if no encoding is specified, the RFC behavior is to interpret it as ascii.

The result is that non-html-encoded characters in the HTML body outside the ascii range will appear rendered incorrectly in compliant email clients.

The mulitpart message generated now:

```
----boundary_10_5d613cd7-52f2-4278-b238-d9041cf4aa11
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: base64

<SNIP>
----boundary_10_5d613cd7-52f2-4278-b238-d9041cf4aa11
Content-Type: text/html
Content-Transfer-Encoding: base64

<SNIP>
----boundary_10_5d613cd7-52f2-4278-b238-d9041cf4aa11--
```

The line `Content-Type: text/html` needs to become `Content-Type: text/html; charset=UTF-8` for this to work correctly.

**Comment by bjcull** [comment]
Fixed the SMTP sender. If you were using a different one let me know.

**Comment by bjcull** [comment]
FluentEmail.Smtp - 2.5.2

**Comment by mqudsi** [comment]
It was indeed the SMTP sender that I was using.

Incredible turnaround time - greatly appreciated!
