### ISSUE TITLE
Sending Multiple Emails - Previous recipients remains in the following emails

### ISSUE THREAD

**Issue by VaclavElias** [lukencode/FluentEmail#117]
Hi,

I am sending multiple emails with MailGun in the foreach loop and every next email is adding previous email address as recipient :(

I am using DI for _email.

``` c#

       await _email.To(emailAlert.Subscriber.Email)
                .Subject("My Subject")
                .Body(GetAlertBody(emailAlert), true)
                .SendAsync();
```

I can see in the MailGun log this, headers has 2 emails (not correct) while the recipient only one which is correct.

```
"message": {
        "headers": {
            "to": "email1@company.co.uk, email2@gmail.com",
            "subject": "My Subject"
        },
        "attachments": [],
        "size": 1175
    },
    "recipient": "email2@gmail.com",
```

Also in the Fiddler Raw I can see this, there shouldn't be email1@company.co.uk:

```
Host: api.mailgun.net

--1cf329c2-d30a-41d4-a1ec-8bce3a24fd60
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=from

Uptime Monitor <DoNotReply@mg.mydomain.com>
--1cf329c2-d30a-41d4-a1ec-8bce3a24fd60
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=to

 <email1@company.co.uk>
--1cf329c2-d30a-41d4-a1ec-8bce3a24fd60
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=to

 <email2@gmail.com>
--1cf329c2-d30a-41d4-a1ec-8bce3a24fd60
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=subject

My Subject
--1cf329c2-d30a-41d4-a1ec-8bce3a24fd60
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=html
```
Am I doing something incorrectly and **SendAsync()** just builds up somehow and doesn't clear the recipient in the header?

Thanks.

**Comment by lukencode** [comment]
Try using IFluentEmailFactory instead of IFluentEmail. Call Create in the
loop for a fresh email instance.

**Comment by VaclavElias** [comment]
Ohh, of course. I haven't read all the docs :(

Thanks, it is working now correctly using **IFluentEmailFactory**.

https://lukencode.com/2018/07/01/send-email-in-dotnet-core-with-fluent-email#send-multiple-emails-in-the-same-scope

**Comment by oocx** [comment]
I ran into the same issue, which embarassingly caused users to receive e-mails with passwords from other users :(

I sill don't really understand why that is the case and where that's mentioned in the docs. I don't mean this as criticism, just as feedback on the usability / discoverability of the api and docs :)

So if I understand correctly, if I change

```
IFluentEmail email; // injected by constructor injection

var message = _email
                .To(email)
// ...
```
to

```
IFluentEmailFactory email; // injected by constructor injection

var message = _email
                .Create()
                .To(email)
// ...
```

it should work as expected (previous recipients won't receive additional emails)?

Regards,
Mathias

**Comment by lukencode** [comment]
Hi mattias

Yes the factory will clear the the email data.

Thanks
Luke

**Comment by lukencode** [comment]
I actually think we should throw an exception if you try send the same
email instance twice.

**Comment by abimr** [comment]
@lukencode 

Yes, please :)

I was lucky and this problem only impacted one user who was trying out a new feature.

**Comment by Jetro223** [comment]
@lukencode It's clear when you read the docs @https://lukelowrey.com/dotnet-email-guide-2021/ but really should be made more transparent in the README directly @github with a "do not use IFluentEmail inside a loop". Just sent passwort reset emails to (fortunately only) 7 users after a short outage of our SMTP :-(

**Comment by rolandow** [comment]
To be honest, I would expect a method called "To" to set the To address, instead of adding a To address. In my use case I would like to send a copy of the mail to another user, with only a changed Subject (Copy of order ...)

**Comment by idbates** [comment]
This issue has just hit on on a production site with duplicate emails sent. Looking at the implementation for the To method I would have thought it safer to first clear the ToAddresses collection in the Data property - it might prevent chaining multiple calls to the To method but its hard to see why someone would do that and not simply pass a semicolon list or list of Address.
