### ISSUE TITLE
Amazon Ses Credentials

### ISSUE THREAD

**Issue by victorjoel44** [lukencode/FluentEmail#121]
Where to I put the amazon ses user and password? im using .net core console to develop the app as a service and guiding myself with smtpsendertests.

  public void SetUp()
        {
            var sender = new SmtpSender(() => new SmtpClient("email-smtp.us-east-1.amazonaws.com")
            {
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.SpecifiedPickupDirectory,
                PickupDirectoryLocation = tempDirectory,
                Port=587,
                Host = "email-smtp.us-east-1.amazonaws.com"
            });
            
            Email.DefaultSender = sender;
            Directory.CreateDirectory(tempDirectory);
        }

**Comment by bjcull** [comment]
Try something like this:
```
    var sender = new SmtpSender(() => new SmtpClient("email-smtp.us-east-1.amazonaws.com", 587)
    {
        EnableSsl = true,
        DeliveryMethod = SmtpDeliveryMethod.Network,
        Credentials = new NetworkCredential("[username]", "[password]")                
    });
```
