### ISSUE TITLE
Cannot find compilation library location for package Microsoft.NETCore.App

### ISSUE THREAD

**Issue by ram3772340** [lukencode/FluentEmail#126]
Hi All,

The below issue is happening when the core web api is deployed in a Windows Server 2008 R2 IIS 7.5
The solution uses FluentEmail with razor templates. The error happens when we use Send Email option using a razor template (**email.UsingTemplateFromFile**). The solution works perfectly fine locally but when deployed in the server I get the below error. I have tried a few suggestions found online with no luck.

**Error:**

> fail: Microsoft.AspNetCore.Server.Kestrel[13]
>       Connection id "0HLH9QFF4TN8Q", Request id "0HLH9QFF4TN8Q:00000002": An unhandled exception was thrown by the application.
> System.InvalidOperationException: Cannot find compilation library location for package **### Microsoft.NETCore.App**
>    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List1 assemblies)
>    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
>    at System.Linq.Enumerable.SelectManySingleSelectorIterator2.MoveNext()
>    at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly)
>    at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
>    at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
>    at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
>    at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(GeneratedRazorTemplate razorTemplate)
>    at RazorLight.TemplateFactoryProvider.CreateFactory(GeneratedRazorTemplate razorTemplate)
>    at RazorLight.TemplateFactoryProvider.CreateFactoryAsync(String templateKey)
>    at RazorLight.RazorLightEngine.CompileTemplateAsync(String key)
>    at RazorLight.RazorLightEngine.CompileRenderAsync(String key, Object model, Type modelType, ExpandoObject viewBag)
>    at FluentEmail.Razor.RazorRenderer.ParseAsync[T](String template, T model, Boolean isHtml)
>    at FluentEmail.Razor.RazorRenderer.FluentEmail.Core.Interfaces.ITemplateRenderer.Parse[T](String template, T model, Boolean isHtml)
>    at FluentEmail.Core.Email.UsingTemplate[T](String template, T model, Boolean isHtml)
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
>    at Griffin.RED.API.Services.Implementations.EmailService.GetFluentEmail(EmailRequestItem emailRequest) in C:\Projects\Griffin\Griffin.RED.API\Services\Implementations\EmailService.cs:line 69
>    at Griffin.RED.API.Services.Implementations.EmailService.SendEmail(EmailRequestItem emailRequest) in C:\Projects\Griffin\Griffin.RED.API\Services\Implementations\EmailService.cs:line 89
>    at Griffin.RED.API.Services.Implementations.ServiceApi.DestinationUpdateProcess(List1 idList) in C:\Projects\Griffin\Griffin.RED.API\Services\Implementations\ServiceApi.cs:line 135
>    at lambda_method(Closure , Object , Object[] )
>    at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
>    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication1 application)
> 

**Server Profile:**

> dotnet --info
> .NET Core SDK (reflecting any global.json):
>  Version:   2.1.403
>  Commit:    04e15494b6
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  6.1.7601
>  OS Platform: Windows
>  RID:         win7-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.403\
> 
> Host (useful for support):
>   Version: 2.1.5
>   Commit:  290303f510
> 
> .NET Core SDKs installed:
>   2.1.302 [C:\Program Files\dotnet\sdk]
>   2.1.400 [C:\Program Files\dotnet\sdk]
>   2.1.401 [C:\Program Files\dotnet\sdk]
>   2.1.403 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Tried Solutions so far (tried different combinations of it):**

-  PreserveCompilationContext True PreserveCompilationContext
-  MvcRazorCompileOnPublish True MvcRazorCompileOnPublish
-  MvcRazorExcludeRefAssembliesFromPublish False MvcRazorExcludeRefAssembliesFromPublish

This is absolutely just a deployment issue. Can anyone suggest a way to get rid of this issue to make the production deployment happen, please?

Many thanks ahead,
R

**Comment by sguryev** [comment]
https://github.com/toddams/RazorLight/issues/203
You should add the `<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>` to the published project regardless of where you have the Templates
