### ISSUE TITLE
Layouts with RazorLight cannot be resolved

### ISSUE THREAD

**Issue by rafalschmidt97** [lukencode/FluentEmail#153]
Hi, 
I can't use layouts in my project. Whatever I do it always ends up with

`
Can not resolve a content for the template "{0}" as there is no project set.You can only render a template by passing it's content directly via string using coresponding function overload
`

I keep all my emails in the same project inside of directory Emails (like Emails/AccountCreated.cshtml). My method looks like that:

```c#
private async Task SendEmail(EmailMessage message, CancellationToken cancellationToken)
    {
      var templatePath = $"{Directory.GetCurrentDirectory()}/Emails/{message.TemplateName}.cshtml";

      await _email
        .To(message.To)
        .Subject(message.Subject)
        .UsingTemplateFromFile(templatePath, message.Model)
        .SendAsync(cancellationToken);
    }
```

Example page:
```c#
@{
    Layout = "Layout.cshtml";
}

<h1>Hello World</h1>
```
Layout.cshtml:
```c#
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title></title>
        <link href="/css/site.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        @RenderBody()
    </body>
</html>
```

Help 🤷‍♂️

**Comment by cja100** [comment]
We have the same issue. Looks like pull request #145 adds support for layouts but it's not in a release or pre release yet. Would it be possible to push a new release?

I'm happy to help with deployment via azure devops if thats the plan.

**Comment by maxence51** [comment]
Yes I'm also interested to this feature. Thank you

**Comment by andersmandersen** [comment]
Anyone who has solved this issue?

**Comment by mtrutledge** [comment]
I believe there was a PR that fixed this issue but a new release has not been done yet

**Comment by cothman** [comment]
Having the same issue. PR already merged, is it planned to be included in a release.

**Comment by cothman** [comment]
I struggled a lot with this issue and finally find the way to fix it. I'm using DI for my Fluentemails and was using AddRazorRenderer() method without passing parameter. I figured out later, from the unit tests  [https://github.com/lukencode/FluentEmail/blob/master/test/FluentEmail.Razor.Tests/RazorTests.cs](url), that I should provide the typeof a root type (in case of embedded resources) in order to use Layouts.

More details are provided in RazorLight docs [https://github.com/toddams/RazorLight#file-source](url)

**Comment by gobijan** [comment]
I went with an approach that just parses a Header partial and prepends it  and Footer partial that is appended to the template string. Works for with the current released version.

**Comment by rafalschmidt97** [comment]
Any updates guys? It's seems like this repo is dead. Alternatives? Does anyone maybe have a package with this PR?

**Comment by rafalschmidt97** [comment]
> I struggled a lot with this issue and finally find the way to fix it. I'm using DI for my Fluentemails and was using AddRazorRenderer() method without passing parameter. I figured out later, from the unit tests [RazorLigh test](https://github.com/lukencode/FluentEmail/blob/master/test/FluentEmail.Razor.Tests/RazorTests.cs), that I should provide the typeof a root type (in case of embedded resources) in order to use Layouts.
> 
> More details are provided in RazorLight docs [doc](https://github.com/toddams/RazorLight#file-source)

Can you provide an example?

**Comment by cothman** [comment]
@rafalschmidt97 , I'm using EmbeddedResources as my email templates and I was adding razor render using DI like this:

```cs
services.AddRazorRenderer()
```

After checking the unit tests of [FluentEMail Razor](https://github.com/lukencode/FluentEmail/blob/master/test/FluentEmail.Razor.Tests/RazorTests.cs) and [RazorLight doc](https://github.com/toddams/RazorLight#embeddedresource-source)
I figured out that I should pass `typeof(rootType)` to 

```cs
services.AddRazorRenderer(typeof(rootType))
```

in order that my code works properly, without doing this RazorLight can't find the TemplateKey.

In your case I think you should pass a RootPath to you RazorRenderer, bellow the code taken from FluentEmail Razor Unit Tests:
```cs
public void Should_be_able_to_use_project_layout_with_viewbag()
	    {
		    var projectRoot = Directory.GetCurrentDirectory();
		    Email.DefaultRenderer = new RazorRenderer(projectRoot);

		    string template = @"
@{
	Layout = ""./Shared/_Layout.cshtml"";
}
sup @Model.Name here is a list @foreach(var i in Model.Numbers) { @i }";

			dynamic viewBag = new ExpandoObject();
			viewBag.Title = "Hello!";
		    var email = new Email(fromEmail)
			    .To(toEmail)
			    .Subject(subject)
			    .UsingTemplate(template, new ViewModelWithViewBag{ Name = "LUKE", Numbers = new[] { "1", "2", "3" }, ViewBag = viewBag});

		    Assert.AreEqual($"<h1>Hello!</h1>{Environment.NewLine}<div>{Environment.NewLine}sup LUKE here is a list 123</div>", email.Data.Body);
	    }
```

**Comment by jzabroski** [comment]
Correct, should be pushing a new RazorLight package to nuget.org any day now (hopefully today).  Was sick all weekend w/ flu and didn't get to it.

**Comment by rafalschmidt97** [comment]
@cothman - wow. So it's not really an issue.

https://github.com/lukencode/FluentEmail/blob/6ea1907a34899b0dc0334c5ff88ec3ab221da89f/src/Renderers/FluentEmail.Razor/FluentEmailRazorBuilderExtensions.cs#L37

Just add `embeddedResourceRootType`. I'll try - thanks guys.

**Comment by cothman** [comment]
@rafalschmidt97 yep :).

Just pay attention to the type of RazorRenderer you want to use there is 3 types as you can see in **FluentEmailRazorBuilderExtensions.cs**. Choose the right one ;)

**Comment by jzabroski** [comment]
It's arguably abstraction overkill that FluentEmail provides much opinion at all about RazorLight API calling conventions.  I'm not sure there is a ton of benefit to hiding RazorLight as a transitive dependency in FluentEmail vs. letting downstream consumers plug in RazorLight.

**Comment by mtrutledge** [comment]
I have updated to the latest and am using
Layouts in my razor views. It is working.

**Comment by bjcull** [comment]
Closing as fixed.

**Comment by rafalschmidt97** [comment]
Some hints for people if you're gonna encourage this problem:

1. Allow embedded resources
```c#
services.TryAdd(ServiceDescriptor.Singleton<ITemplateRenderer, RazorRenderer>(sp =>
        new RazorRenderer(typeof(Program)))); // Type is required for embedded resources
```
2. Allow views discovery
```c#
<EmbeddedResource Include="Views\**\*.cshtml" />
```
3. Path for layout is really important!
```c#
@{
  //Layout = "Layout.cshtml";
  // Layout = "./pl/Layout.cshtml"; // NOPE
  // Layout = "Views/pl/Layout.cshtml"; // 😭
  Layout = "Views.pl.Layout.cshtml"; // FINALLY!
  // Layout = "Skelvy.WebAPI.Views.pl.Layout.cshtml"; // NOT TODAY BABY!
}
```
4. For production purposes
```c#
    <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish> // NOPE!
   <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish> // YES!
```

Thanks guys again. Have a good day!

**Comment by dontbesorry80** [comment]
@rafalschmidt97 
Thank you so much for your reply above. This worked for me. I appreciate the time you spent doing this for us.
