### ISSUE TITLE
An asynchronous call is already in progress

### ISSUE THREAD

**Issue by rafalschmidt97** [lukencode/FluentEmail#154]
SMTP it's not implemented properly probably. I cannot send two messages simultaneously.

```
 Unexpected Server Exception:
System.InvalidOperationException: An asynchronous call is already in progress. It must be completed or canceled before you can call this method.
   at System.Net.Mail.SmtpClient.SendAsync(MailMessage message, Object userToken)
   at FluentEmail.Smtp.SendMailEx.SendMailExImplAsync(SmtpClient client, MailMessage message, CancellationToken token)
   at FluentEmail.Smtp.SmtpSender.SendAsync(IFluentEmail email, Nullable`1 token)
   at FluentEmail.Core.Email.SendAsync(Nullable`1 token)
```

Take a look here: https://stackoverflow.com/questions/50036795/getting-error-while-sending-bulk-email-an-asynchronous-call-is-already-in-progr

**Comment by candidodmv** [comment]
I'm with the same issue here

**Comment by candidodmv** [comment]
@rafalschmidt97 may you need to use IFluentEmailFactory instead of IFluentEmail, so you can do something like this:
```
foreach(mail in mails){
await _emailFactory.Create().To(mail.destination)
                        .Subject(mail.subject)
                        .Body(mail.message)
                        .SendAsync()
}
```

**Comment by McPhale** [comment]
I had the same issue with an API endpoint that sends out emails using smtp sender.  If it gets called while while it's still processing the first request this happens. Ended up redesigning the way the endpoint is triggered by the client.

**Comment by PeterLarsen-CPH** [comment]
The problem is the SMTP client, which (as mentioned above) cannot handle more than one mail at the time. So you need to tell FluentEmail how to get the next SmtpClient instance when needed:

```
serviceCollection.AddSingleton<FluentEmail.Core.Interfaces.ISender>(x =>
{
    return new FluentEmail.Smtp.SmtpSender(new Func<SmtpClient>(() =>
    {
        var client = new SmtpClient("SMTP server", 25);
        client.SendCompleted += delegate (object sender, System.ComponentModel.AsyncCompletedEventArgs e)
        {
            if (e.Error != null)
                System.Diagnostics.Trace.TraceError($"Error sending email: {e.Error.Message}");
            if (sender is SmtpClient)
                (sender as SmtpClient).Dispose();
        };
        return client;
    }));
});
```
SmtpSender controls how to create the next SmtpClient and by injecting your own instance then you can decide what should happen.

**Comment by Yukon** [comment]
I have found the cause of the issue to be the SmtpClient is reused throughout the entire lifetime of the application. A fix can be made in applications without pulling my patch by explicitly using the function version of `AddSmtpSender`. For example `AddSmtpSender(() => new SmtpSender("smtp.example.com", 25)` instead of `AddSmtpSender("smtp.example.com", 25)`.

**Comment by NickVandenberghe** [comment]
This solution caused me to have another problem.
The smtpclient gets disposed.

I use emailfactory to create my mails and to send them.
I also send mails whenever an error occurs.

When the first mails gets send and later on in the code an error occurs, i get the message that the smtpclient is disposed when trying to send an errorMail

**Comment by PeterLarsen-CPH** [comment]
> 
> 
> This solution caused me to have another problem.
> The smtpclient gets disposed.
> 
> I use emailfactory to create my mails and to send them.
> I also send mails whenever an error occurs.
> 
> When the first mails gets send and later on in the code an error occurs, i get the message that the smtpclient is disposed when trying to send an errorMail

What solution cause problems?

**Comment by NickVandenberghe** [comment]
> For example AddSmtpSender(() => new SmtpClient("smtp.example.com", 25)) instead of AddSmtpSender("smtp.example.com", 25).

I already fixed this now.
I configured a smtpclient before adding it to the `AddSmtpSender` function
I fixed my error by configuring the smtpclient in the `AddSmtpSender` function
