### ISSUE TITLE
Update FluentEmail.Mailgun nuget package

### ISSUE THREAD

**Issue by aqbjteddy** [lukencode/FluentEmail#167]
Hi Luke,

Please update the nuget package named "FluentEmail.Mailgun", I found there were some important changes in master branch, like adding "MessageId" for SendResponse class, that was awesome!

Thanks

**Comment by aqbjteddy** [comment]
@lukencode Can you spend some time on this issue? Thanks.

**Comment by McPhale** [comment]
I've found I have more luck hosting my own clone of master in an internal nuget package. That might be an option for you if the maintainers aren't able to get to it in time.

**Comment by lukencode** [comment]
I have now merged and updated the packages. Sorry for the delay.
