### ISSUE TITLE
Incompatibility with .NET Core 3.0?

### ISSUE THREAD

**Issue by kanazaca** [lukencode/FluentEmail#175]
Hi :)

I'm using .net core and i'm getting this error 
`TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.Razor.Extensions.NamespaceDirective' from assembly 'Microsoft.AspNetCore.Mvc.Razor.Extensions, Version=3.0.0.0, Culture=neutral, `

Since .net core 3.0 `NamespaceDirective` was moved to `Microsoft.AspNetCore.Razor.Language.Extensions`.

Is this what is causing the issue? 

Thanks :)

**Comment by IGx89** [comment]
FYI it appears to be an issue in RazorLight and not FluentEmail. See https://github.com/toddams/RazorLight/issues/267#issuecomment-537951888 -- the author is just waiting for a PR to fix it.

**Comment by kanazaca** [comment]
> FYI it appears to be an issue in RazorLight and not FluentEmail. See [toddams/RazorLight#267 (comment)](https://github.com/toddams/RazorLight/issues/267#issuecomment-537951888) -- the author is just waiting for a PR to fix it.

Oh nice :) So i can close this.

**Comment by matthewblott** [comment]
Unfortunately the RazorLight maintainer says he's too busy and he's been waiting for a PR for some time (it's been in beta for ages now). It may be a long while before FluentEmail can be ported to 3.0 while it has a dependency on RazorLight.

**Comment by maxence51** [comment]
A workaround for the moment is to manually call RazorLight rendering and set it to the body.
I used @whyseco package https://www.nuget.org/packages/RazorLight.NetCore3/

`_razorLightEngine = new RazorLightEngineBuilder()
.UseEmbeddedResourcesProject(this.GetType()).UseMemoryCachingProvider().Build();
`
...
```
string renderedHtml = await _razorLightEngine.CompileRenderStringAsync(GetHashString(razorViewAsString),razorViewAsString, 
 emailMetadata.EmailViewModel);
 email.Body(renderedHtml, isHtml:true);

  private static string GetHashString(string inputString)
  {
      StringBuilder stringBuilder = new StringBuilder();
      foreach (byte num in SHA256.Create().ComputeHash(Encoding.UTF8.GetBytes(inputString)))
            stringBuilder.Append(num.ToString("X2"));
       return stringBuilder.ToString();
 }
```
