### ISSUE TITLE
Razor layout status

### ISSUE THREAD

**Issue by agrath** [lukencode/FluentEmail#179]
Hi all,
Just checking, is the Layout support merged in PR#145 to master available in the myget 2.8.0 beta? 
I have just upgraded to the beta (as I wanted layout support) but I'm still getting RenderBody not defined and I'm not sure if I've set it up wrong or if the functionality is not in myget yet.

**Comment by bjcull** [comment]
The PR is merged, and the tests are passing. I'd check out this test for details https://github.com/lukencode/FluentEmail/blob/6ea1907a34899b0dc0334c5ff88ec3ab221da89f/test/FluentEmail.Razor.Tests/RazorTests.cs#L113
Let me know if there's still trouble.

**Comment by agrath** [comment]
Thanks @bjcull Ben

I am sure it wasn't working for me (otherwise I wouldn't have raised this [albeit brief] issue),

However looking at my solution, it looks like I just got rid of the layout and put it in each of my templates (there are only 3)
I have also since moved this to use embedded resources as I had issues with getting .net core to deploy the physical view files.

Based on your reply, I think we should close this issue and I can raise a new issue with more detailed steps to reproduce (assuming I can) when I move this project back to using layouts (probably when I add more emails) 

Thank you for your time.

**Comment by jzabroski** [comment]
Hi agrath, there is an open issue in Razorlight for IncludeAsynx with a _Layout.cshtml. willing to take PRs.
