### ISSUE TITLE
Mailgun Recipient-Variables

### ISSUE THREAD

**Issue by DWalkit** [lukencode/FluentEmail#201]
This property doesn't seem to be included as a msg option.  Has anyone discovered a way to use Mailgun's Recipient-Variables with batch sending?

**Comment by belidzs** [comment]
Not very elegant but you can add as an email header:

```csharp
email.Data.Headers.Add("X-Mailgun-Variables", "{ \"variable_name\" : \"value\" }");
```

**Comment by DWalkit** [comment]
Thank you belidzs.  

I tried adding "X-Recipient-Variables" to the header last week but with batch sending Mailgun seems to need that variable in the body, not the header.  I ended up going with a basic RestSharp submission and everything works as expected.  

Was initially sad that I lost Razor templating but with a batch I'm only sending one "body" and having Mailgun insert the variables to customize each message anyway!  So really there's no point in FluentEmail offering this parameter!  I'm closing this "issue".
