### ISSUE TITLE
SendAsync() does not clean "To"

### ISSUE THREAD

**Issue by frankhaugen** [lukencode/FluentEmail#221]
I have the need to send multiple emails with different templates to many recipients. I would expect something like:
```c#
foreach (var notification in emailNotifications)
{
    await _fluentEmail
        .To(notification.ToAddress)
        .Subject(notification.Subject)
        .UsingTemplate(template, notification)
        .SendAsync();
}
```
... To send one email to one person successively

What actually happens when this code is executed, is that the first recipient gets an email addressed to them, then the second gets sent to both the first and the second email, then it continues until the foreach ends

This caused an interesting situation where everyone got spammed down by emails this morning

**Comment by frankhaugen** [comment]
Maybe a "SendAndClear()" method, would be appropriate

**Comment by lukencode** [comment]
The email factory is the supported way to handle this calling FluentEmailFactory.Create() will give you a fresh email to send. I am considering throwing an exception when you try to send the same email twice.

**Comment by hisuwh** [comment]
@lukencode this is not really expected at all and you should really update your documentation with a HUGE red warning banner - this is _**EXTREMELY**_ dangerous - (imagine password reset emails going out to multiple people?!?)!

TBH you should probably deprecate IFluentEmail and make FluentEmailFactory the standard as I do not understand why would ever want the OPs behaviour.
