### ISSUE TITLE
Razor Tag Helpers?

### ISSUE THREAD

**Issue by ryburn52** [lukencode/FluentEmail#225]
I'm looking at implementing https://github.com/XmlmXmlmX/InkyTagHelpers with Fluent Email so we don't have to write html like its the 90's. The sample project looks like it uses razor tag helpers to convert component style syntax into email safe html.

```
<container>
    <row class="header">
        <columns>
            <spacer size="16"></spacer>
            <h4 class="text-center">Hello World</h4>
        </columns>
    </row>
</container>
```

This gets rendered as a bunch of tables, save for email. 
Is there a way to configure the Razor engine that FluentEmail uses to enable Tag Helpers? It looks like in ASP.net MVC you do this via `_ViewImports.cshtml`

```
@using InkyTagHelpers
@using InkyTagHelpers.Web
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, InkyTagHelpers
```
The other think i would probably need to do is include the foundation-emails.css. Can you specify Layouts to use with the emails?

**Comment by ryburn52** [comment]
Based on what i could find it looks like Razor Light does not support tag helpers yet. 
https://github.com/toddams/RazorLight/issues/21

**Comment by lukencode** [comment]
That is a shame, we are limited by Razor Light here
