### ISSUE TITLE
FluentEmail.Graph in separate repo

### ISSUE THREAD

**Issue by DavidDeSloovere** [lukencode/FluentEmail#232]
Hello,

As there is no version of the contributed FluentEmail.Graph in this repo on nuget:
I took the liberty of copying FluentEmail.Graph into a separate repo and publish it to nuget. With slight modifications.

https://github.com/NatchEurope/FluentEmail.Graph
https://www.nuget.org/packages/FluentEmail.Graph

The original code could be removed from this project.

**Comment by lukencode** [comment]
Thanks @DavidDeSloovere I have merged Graph into the main report (great timing as I need it for my day job!). Happy for the package to be maintained either separately or centrally here. Let me know what you want to do.
