### ISSUE TITLE
Liquid Template with complex model not working

### ISSUE THREAD

**Issue by soulox** [lukencode/FluentEmail#265]
Hi,

I have a blazor project with the liquid template in place but the layout only show the first level properties
Example if a model has something like 
{{Product.Name}}
{{Product.Category.Name}}

Only Product.Name is showing 
Product.Category.Name is not showing anthing

Thank you

**Comment by soulox** [comment]
Do you have any update on this?

**Comment by sebastienros** [comment]
Fluid is "opt-in" by default and sub properties need to be registered. There is an option however to accept any property:

It would look like this, but I don't know how it can be configured in FluentEmail.

```
templateOptions.MemberAccessStrategy = UnsafeMemberAccessStrategy.Instance;
```

**Comment by nickj886** [comment]
Hi @soulox Did you find a solution for this?

**Comment by soulox** [comment]
No I didn't yet

**Comment by sebastienros** [comment]
I found an example in the tests that shows how to customize TemplateContext, that would work.

https://github.com/lukencode/FluentEmail/blob/a94b1f3d084476dfeaeedd1845cdecd2b6718dbc/test/FluentEmail.Liquid.Tests/LiquidTests.cs#L32

I think a better approach would be to expose a `TemplateOptions` instance in the options such that this can be done once. It might require updating to Fluid 2.0 (https://github.com/lukencode/FluentEmail/pull/278)

**Comment by nickj886** [comment]
I threw this together shortly after posting my comment

`public static class LiquidRendererOptionsHelper
    {
        public static LiquidRendererOptions Create()
        {
            return new LiquidRendererOptions
            {
                FileProvider = new NullFileProvider()
            };
        }

        public static LiquidRendererOptions Create<TModel>()
            where TModel : class
        {
            return new LiquidRendererOptions
            {
                ConfigureTemplateContext = (templateContext, obj) =>
                {
                    var memberAccessor = new MemberAccessor();
                    templateContext.MemberAccessStrategy.RegisterClassMembers(typeof(TModel), memberAccessor);
                },
                FileProvider = new NullFileProvider()
            };
        }

        public static LiquidRendererOptions Create(string rootPath)
        {
            return new LiquidRendererOptions
            {
                FileProvider = new PhysicalFileProvider(rootPath)
            };
        }

        private static void RegisterClassMembers(this Fluid.IMemberAccessStrategy memberAccessStrategy, Type modelType, Fluid.IMemberAccessor memberAccessor, HashSet<Type> knownTypes = null)
        {
            if (knownTypes == null)
                knownTypes = new HashSet<Type>();

            if (knownTypes.Contains(modelType))
                return;

            knownTypes.Add(modelType);

            foreach (var property in modelType.GetProperties())
            {
                if (!property.CanRead)
                    continue;

                if (!property.GetMethod.IsPublic)
                    continue;

                var notMappedAttribute = property.CustomAttributes?.FirstOrDefault(o => o.AttributeType == typeof(NotMappedAttribute));
                if (notMappedAttribute != null) 
                    continue;

                memberAccessStrategy.Register(modelType, property.Name, memberAccessor);

                if (!property.PropertyType.IsClass)
                    continue;
                
                if (property.PropertyType == typeof(string))
                    continue;

                if (property.PropertyType == typeof(DateTime))
                    continue;

                if (typeof(System.Collections.IEnumerable).IsAssignableFrom(property.PropertyType))
                    memberAccessStrategy.RegisterClassMembers(property.PropertyType.GetGenericArguments()[0], memberAccessor, knownTypes);
                else
                    memberAccessStrategy.RegisterClassMembers(property.PropertyType, memberAccessor, knownTypes);
            }
        }
    }

    public class MemberAccessor : Fluid.IMemberAccessor
    {
        public object Get(object obj, string name, Fluid.TemplateContext templateContext)
        {
            var objType = obj.GetType();
            var property = objType.GetProperty(name);
            return property.GetValue(obj);
        }
    }`

usage:

`var email = new FluentEmail.Core.Email();
email.Renderer = new LiquidRenderer(LiquidRendererOptionsHelper.Create<MyClass>());'`

**Comment by nickj886** [comment]
I threw this together shortly after posting my comment. It should help you out

```
public static class LiquidRendererOptionsHelper
{
public static LiquidRendererOptions Create()
{
return new LiquidRendererOptions
{
FileProvider = new NullFileProvider()
};
}

    public static LiquidRendererOptions Create<TModel>()
        where TModel : class
    {
        return new LiquidRendererOptions
        {
            ConfigureTemplateContext = (templateContext, obj) =>
            {
                var memberAccessor = new MemberAccessor();
                templateContext.MemberAccessStrategy.RegisterClassMembers(typeof(TModel), memberAccessor);
            },
            FileProvider = new NullFileProvider()
        };
    }

    public static LiquidRendererOptions Create(string rootPath)
    {
        return new LiquidRendererOptions
        {
            FileProvider = new PhysicalFileProvider(rootPath)
        };
    }

    private static void RegisterClassMembers(this Fluid.IMemberAccessStrategy memberAccessStrategy, Type modelType, Fluid.IMemberAccessor memberAccessor, HashSet<Type> knownTypes = null)
    {
        if (knownTypes == null)
            knownTypes = new HashSet<Type>();

        if (knownTypes.Contains(modelType))
            return;

        knownTypes.Add(modelType);

        foreach (var property in modelType.GetProperties())
        {
            if (!property.CanRead)
                continue;

            if (!property.GetMethod.IsPublic)
                continue;

            var notMappedAttribute = property.CustomAttributes?.FirstOrDefault(o => o.AttributeType == typeof(NotMappedAttribute));
            if (notMappedAttribute != null) 
                continue;

            memberAccessStrategy.Register(modelType, property.Name, memberAccessor);

            if (!property.PropertyType.IsClass)
                continue;
            
            if (property.PropertyType == typeof(string))
                continue;

            if (property.PropertyType == typeof(DateTime))
                continue;

            if (typeof(System.Collections.IEnumerable).IsAssignableFrom(property.PropertyType))
                memberAccessStrategy.RegisterClassMembers(property.PropertyType.GetGenericArguments()[0], memberAccessor, knownTypes);
            else
                memberAccessStrategy.RegisterClassMembers(property.PropertyType, memberAccessor, knownTypes);
        }
    }
}

public class MemberAccessor : Fluid.IMemberAccessor
{
    public object Get(object obj, string name, Fluid.TemplateContext templateContext)
    {
        var objType = obj.GetType();
        var property = objType.GetProperty(name);
        return property.GetValue(obj);
    }
}
```

usage:

```
var email = new FluentEmail.Core.Email();
email.Renderer = new LiquidRenderer(LiquidRendererOptionsHelper.Create<MyClass>());
```

**Comment by soulox** [comment]
Do you have any update on this issue?
