### ISSUE TITLE
Support Fluid 2.0

### ISSUE THREAD

**Issue by ronniebarker** [lukencode/FluentEmail#270]

**Comment by mdekok** [comment]
I'm working on a project that uses Fluid both directly (generating HTML) as indirectly through FluentEmail.Liquid. The lastest Fluid.Core version is 2.2.0. FluentEmail.Liquid still depends on Fluid.Core 1.0.0. There're breaking changes between 1.0.0 and 2.2.0.
For now I build my own version of FluentEMail.Liquid.dll including the pull request mentioned above, to get it working. It would be nice to get back to an updated nuget package including a recent Fluid.Core. The pull request uses 2.0.13 of Fluid.Core, I tested with 2.2.0 which seems to work as well.

**Comment by avoxm** [comment]
Any update on this ?
