### ISSUE TITLE
RazorLight.Compilation.TemplateCompilationException: Failed to compile generated Razor template

### ISSUE THREAD

**Issue by affableashish** [lukencode/FluentEmail#275]
I'm creating a `.NET 5 worker service` app that watches few other apps and sends email when required.
I'm using [FluentEmail][1] to send those emails and everything works fine, until I deploy the app.

When I deploy the app and it attempts to send an email, it throws this exception:

    RazorLight.Compilation.TemplateCompilationException: Failed to compile generated Razor template:
    - (3:35) The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (3:10) The type 'Type' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (35:37) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (38:66) 'GeneratedTemplate.ExecuteAsync()': return type must be 'Task' to match overridden member 'TemplatePageBase.ExecuteAsync()'
    - (38:66) The type 'Task' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (40:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (41:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (42:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (43:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (53:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (69:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (84:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (44:19) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (92:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (47:20) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (100:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (50:20) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (108:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (53:19) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (116:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    - (124:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
    See CompilationErrors for detailed information
       at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(IGeneratedRazorTemplate razorTemplate)
       at RazorLight.Compilation.RazorTemplateCompiler.CompileAndEmit(RazorLightProjectItem projectItem)
       at RazorLight.Compilation.RazorTemplateCompiler.OnCacheMissAsync(String templateKey)
    --- End of stack trace from previous location ---
       at RazorLight.EngineHandler.CompileTemplateAsync(String key)
       at RazorLight.EngineHandler.CompileRenderAsync[T](String key, T model, ExpandoObject viewBag)
       at CallSite.Target(Closure , CallSite , Object )
       at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
       at FluentEmail.Razor.RazorRenderer.ParseAsync[T](String template, T model, Boolean isHtml)
       at FluentEmail.Razor.RazorRenderer.FluentEmail.Core.Interfaces.ITemplateRenderer.Parse[T](String template, T model, Boolean isHtml)
       at FluentEmail.Core.Email.UsingTemplateFromFile[T](String filename, T model, Boolean isHtml)
       at WatchDog.Services.NotificationService.SendEmailAsync[TModel](String subject, String fileName, TModel model) in C:\Users\SomeOne\source\repos\WatchDog\WatchDog\Services\NotificationService.cs:line 41

My setup looks like this:

|Views Folder|References|
|--|--|
|<img src="https://i.stack.imgur.com/v55J9.png/200" width="300" />|<img src="https://i.stack.imgur.com/RqS1d.png/25" width="200" />|

| Views Folder |
| -- |

I added the Views folder and please note that this is a `.NET 5 Worker Service` project (if that matters instead of it being some Web project).

| Program.cs file: |
| -- |

Inside the ConfigureServices, I've added the `RazorRenderer` as:

    //Set email service using FluentEmail
     services.AddFluentEmail("appname@domain.com")
     .AddRazorRenderer(@$"{Directory.GetCurrentDirectory()}/Views/")
     .AddSmtpSender("smtp.somesmtp.com", 25)
     .AddSmtpSender(new System.Net.Mail.SmtpClient() { });

| NotificationService.cs file: |
| -- |

    private async Task SendEmailAsync<TModel>(string subject, TModel model)
    {
        try
        {
            using (var scope = _serviceProvider.CreateScope())
            {
                var email = await scope.ServiceProvider.GetRequiredService<IFluentEmail>()
                        .To(string.Join(";", _emailRecipients))
                        .Subject(subject)
                        .UsingTemplateFromFile("./Views/Emails/SomeReport.cshtml", model)
                        .SendAsync();
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to send email. Check exception for more information.");
        }
    }

| SomeReport.cshtml file: |
| -- |

`SomeReport.cshtml` is inside `Views\Emails\SomeReport.cshtml` which looks like this:

    @using System;
    @using RazorLight;
    @using System.Collections.Generic;
    @using WatchDog.Models;
    
    @model IEnumerable<SomeReport>
    @{
        Layout = "./Shared/_Layout.cshtml";
    }
    
    @* Work with the Model here... *@

| _Layout.cshtml file: |
| -- |

`_Layout.cshtml` is inside `Views\Shared\_Layout.cshtml` which looks like this:

    @using RazorLight;
    @* Some common layout styles here *@
    @RenderBody()

| WatchDog.csproj file: |
| -- |

I've also added `PreserveCompilationContext` and `PreserveCompilationReferences`:

    <PropertyGroup>
      <TargetFramework>net5.0</TargetFramework>
      <PreserveCompilationContext>true</PreserveCompilationContext>
      <PreserveCompilationReferences>true</PreserveCompilationReferences>
    </PropertyGroup>

I've looked at everywhere and still haven't found a solution to this.
Please help.

Thanks!

  [1]: https://github.com/lukencode/FluentEmail

**Comment by jzabroski** [comment]
I am a little confused why you would copy-paste so much config stuff vs. just create a GitHub repository with the full repro.

I have not used .NET 5 worker services before.  In fact, reading this issue was the first time I learned about it, so thank you for sharing.

Based on reading the docs, I would probably want to see your file csproj, as https://docs.microsoft.com/en-us/dotnet/core/extensions/workers#the-project-file basically says you need to use the worker service SDK.

That said, the issue could be as simple as .NET 5 trimming.  I am not sure how to disable trimming - I think you have to use `<IsTrimmable>false</IsTrimmable>`

**Comment by affableashish** [comment]
Hi @jzabroski, thank you for the reply.
I unfortunately wasn't able to create a repo of this code as this is from my work and I can't publish code outside of work.

And you're right, it was something related to publish.
And this answer fixed the issue for me:

https://stackoverflow.com/a/68622890/8644294

Thank you!

**Comment by jzabroski** [comment]
PublishTrimmed false and IsTrimmable are very similar so not so not surprised that works but am surprised people would pass in p:PublishTrimmed=true from command line. It seems extremely bad practice to customize your pack differently and outside your csproj as developers will debug the app in a different context than actually deployed
