### ISSUE TITLE
Trying to install nuget FluentEmail.Razor on Framework 4.6.1

### ISSUE THREAD

**Issue by michael34** [lukencode/FluentEmail#44]
I'm getting this:
Could not install package 'FluentEmail.Razor 2.0.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Do I need to change my target framework?
My understanding was .NET-Standard is included in .NET-Framwork 4.6. Am I wrong?
https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by IGx89** [comment]
Looks like support for .NET Framework 4.5.1 was missed being added to its project.json. I've submitted a PR to address that.

**Comment by bjcull** [comment]
This should be fixed now. Though I did run into problems on a 4.5.1 project, a 4.6 was fine.

If you do have trouble, try installing RazorLight first. Seemed to help.
