### ISSUE TITLE
SmtpSender disposes itself after first send

### ISSUE THREAD

**Issue by IGx89** [lukencode/FluentEmail#46]
I'm using Email.DefaultSender to set up SmtpSender as the sender, but upon the first send the SmtpClient object in SmtpSender is disposed, preventing any further sends until I set Email.DefaultSender to a new SmtpSender object.

That behavior is definitely not intentional I'm guessing? The root cause appears to be that SmtpSender is calling its own Dispose method after it sends an email (!).

Code to reproduce:

```
Email.DefaultSender = new SmtpSender();

Email
        .From("john@email.com")
        .To("bob@email.com", "bob")
        .Subject("hows it going bob")
        .Body("yo dawg, sup?")
	.Send();

Email
        .From("john@email.com")
        .To("bob@email.com", "bob")
        .Subject("hows it going bob")
        .Body("yo dawg, sup?")
	.Send();
// throws ObjectDisposedException
```

**Comment by IGx89** [comment]
@anthonyvscode, I'm CC'ing you since you were recently working on that code. You didn't cause the bug AFAICS, though you may have insight into this issue?

**Comment by mxmissile** [comment]
you need to new up the client every time you `Send()` also, if you want to re-use the client you'll need to write your own `SmtpSender`, looking at the code its trivial

**Comment by IGx89** [comment]
Yep, those are two workarounds for the bug -- I'm doing the former.

**Comment by Valeriy1991** [comment]
Hello! It seems to me that it is not a good idea that default `SmtpSender` hides information about the disposing the internal smtp client - this is not obvious to the consumer (ie to the developer). Maybe, `ISender` should also be` IDisposable`?

**Comment by bjcull** [comment]
#89 now spins up and disposes the SmtpClient using the given function. Not ideal, but not broken.

**Comment by kakone** [comment]
I agree that we should be able to pass our own SmtpClient and it should not be disposed by the Send method.
So, I created https://github.com/lukencode/FluentEmail/pull/98/ to fix this.
