### ISSUE TITLE
FluentEmail.SendGrid NuGet package has a dependency on FluentEmail.Core (>= 2.1.0-beta0) which doesn't exist in NuGet

### ISSUE THREAD

**Issue by judowalker** [lukencode/FluentEmail#53]
I can't install the FluentEmail.SendGrid NuGet package because it has a dependency on FluentEmail.Core (>= 2.1.0-beta0) which doesn't exist in NuGet. I have to explicitly install FluentEmail.Core 2.0.3.

**Comment by bjcull** [comment]
Updated the docs to show prerelease MyGet feed and bumped versions as per 90235761fd65ead5d0087eca6e91ee9db06bd7fd

Pushed 2.1.0 to nuget.

**Comment by judowalker** [comment]
Thanks for the quick fix.
