### ISSUE TITLE
FluentEmail with HangFire

### ISSUE THREAD

**Issue by qz2rg4** [lukencode/FluentEmail#55]
Hi great package.

I have a problem when using Hangfire Background Processing package http://www.hangfire.io.

If I try to schedule an email for example

 `BackgroundJob.Schedule(() => FluentEmail.Email.From("FromEmail@example.com").To("ToEmail@example.com").Subject("Subject").Body("Body").Send()), TimeSpan.FromSeconds(30));   `

I get a System.InvalidOperationException: **A from address must be specified.**
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at FluentEmail.Email.Send()

but when I wrap it in a static class it works 
ie

```
 public static void email(string FromEmail,string ToEmail,string Subject,string Body)
        {
             FluentEmail.Email.From(FromEmail).To(ToEmail).Subject(Subject).Body(Body).Send();
           

        }
 BackgroundJob.Schedule(() => EMS.App_Helpers.MyHelpers.email("email@exampe.com","email@emample.com","Test","test"), TimeSpan.FromSeconds(30));   
```

Any Ideas?

**Comment by mika76** [comment]
Probably something to do with how Hangfire serializes it's tasks. Check https://www.hangfire.io/blog/2014/05/10/are-your-methods-ready-to-run-in-background.html

**Comment by lukencode** [comment]
Hi @qz2rg4 I think @mika76  is right - this is more of a hangfire issue than fluentemail
