### ISSUE TITLE
Can't install package on .NET 4.0 target

### ISSUE THREAD

**Issue by picrap** [lukencode/FluentEmail#61]
When I try to install FluentEmail.Smtp, I get the following error:
`Could not install package 'FluentEmail.Smtp 2.0.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`
And when I look at the package, I understand: there is only a net451 folder, so currently the package can not be installed on .NET 4.0 targetting applications.
If you place the assemblies in a 'net40' folder, it will do the trick 😄

**Comment by bjcull** [comment]
Haha good workaround. Minimum support will be 4.6.1 from #66 onward. I suggest you upgrade your projects, as 4.0 is quite old now.

**Comment by picrap** [comment]
This is a very common mistake in open source to think that everyone can target any framework without constraints 😛 
The fact is that I'm stuck with version 4.0 because I own a company selling software to people still running Windows XP / 2003 (not all of them of course, but some of them for sure). It's not my choice, I wouldn't make the same, but sometimes historical reasons make that this still exists. This is why I'm still working with 4.0, which is, right, quite old now 😄 
So no problem; I'll find some workaround 😉 . Thanks anyway for answer and for the library.
