### ISSUE TITLE
RazorRenderer doesn't work on netcoreapp2.0

### ISSUE THREAD

**Issue by snovak7** [lukencode/FluentEmail#63]
I get an exception that some Razor couldn't load, or be found.

**Comment by totalprogrammi** [comment]
RazorRenderer uses RazorLight, which is not compatible with .net core 2.0. Any workaround?

**Comment by bjcull** [comment]
We have to wait for the razorlight upgrade before we can upgrade. Not sure
if there's a workaround yet. Seems like there should be. I'll look into it.

**Comment by snovak7** [comment]
Interesting. I found it here https://github.com/toddams/RazorLight/issues/63. By the comments first version  should be in mid September.

**Comment by alexzaytsev-newsroomly** [comment]
What i get in .net core 2.0 app is :
`System.TypeLoadException: 'Method 'get_Size' in type 'Microsoft.Extensions.Caching.Memory.CacheEntry' from assembly 'Microsoft.Extensions.Caching.Memory, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.'`

**Comment by bjcull** [comment]
Fixed by #66 (netstandard2.0)
