### ISSUE TITLE
Binary attachments gets incorrectly converted to Base64 when using SendGrid

### ISSUE THREAD

**Issue by HakanL** [lukencode/FluentEmail#64]
If you attach a binary file (like jpeg, xls-file, etc) and use SendGrid then you'll get incorrectly converted Base64-data in the email. The issue is that GetAttachmentBase64String is using Encoding.Unicode to convert the binary stream to a string, which isn't correct.

**Comment by bjcull** [comment]
Fixed in 2.0.2 - https://www.nuget.org/packages/FluentEmail.SendGrid/2.0.2
