### ISSUE TITLE
How to disable SSL on SMTP?

### ISSUE THREAD

**Issue by biapar** [lukencode/FluentEmail#68]
ERROR U4HDRedSpaceBusinessLogic.Controllers.HDManagerAppController - failed to send password notification
System.Net.Mail.SmtpException: SSL non deve essere abilitato per i metodi di invio tramite directory di prelievo.
   in System.Net.Mail.SmtpClient.SendAsync(MailMessage message, Object userToken)
   in System.Net.Mail.SmtpClient.SendMailAsync(MailMessage message)
   in FluentEmail.Smtp.SmtpSender.<SendAsync>d__8.MoveNext()

**Comment by ThisNoName** [comment]
This should work

    var sender = new SmtpSender(new SmtpClient("localhost"))
    {
        UseSsl = false
    };
    Email.DefaultSender = sender;

**Comment by bjcull** [comment]
Smtp package now lets you supply a SmtpClient factory to customise your SmtpClient.
