### ISSUE TITLE
A Mandrill sender

### ISSUE THREAD

**Issue by justSteve** [lukencode/FluentEmail#70]
I'm migrating a mvc5 app to mvc core using the Core 2 Web project template. I'd love to add a Mandrill sender project but looking like there's going to be dependency issues. When I open the FluentEmail in VS2017, clean and build I'm getting a whole slew of 'Detected package downgrade' messages. Any actions i should be taking before an initial build?

**Comment by bjcull** [comment]
Oh I haven't merged the .net core 2 update yet. You can take a look at the
branch for now if you want (netstandard2) , but I'll merge this probably
tomorrow.

Cheers,

Ben

**Comment by bjcull** [comment]
The .NET Standard 2.0 stuff is all merged now. Can you pull down master and try building again?
