### ISSUE TITLE
Support Inline Images

### ISSUE THREAD

**Issue by dapug** [lukencode/FluentEmail#74]
I see an Attach() method on FluentEmail.Core.Email, but no **Inline** attachment ability. 

**Business value:**
This is important for email body's/templates that contain inline images (even for simple things like a company **logo**, so this is a pretty big deal).

Examples of MailGun supporting inline here:
https://documentation.mailgun.com/en/latest/api-sending.html#sending
https://documentation.mailgun.com/en/latest/user_manual.html#sending-via-api

**Comment by dapug** [comment]
Added PR for this. It would be nice to have in NuGet for my projects rather than my forked code. So an official release with this would be nice!

**Comment by dapug** [comment]
Now that I went to the effort, I'm thinking perhaps I jumped the gun on this.  CID embedded image is 1 of 2 options for inline image, and its debatable that perhaps it's the less optimal way.

Read here for more:
https://sendgrid.com/blog/embedding-images-emails-facts/

Still, perhaps there are cases where it is critical?

**Comment by mxmissile** [comment]
I wish everyone would agree on a workable standard.  The 3 options all have too many cons each.

**Comment by bjcull** [comment]
I'm happy with the solution being CID as it appears to be the most widely supported (if not outdated) solution. I'd personally go with using normal image tags, but it's good to get this support in as well.
