### ISSUE TITLE
Email template not rendering model data

### ISSUE THREAD

**Issue by CalebJTSmith** [lukencode/FluentEmail#77]
This may be me missing something really obvious, but I am not able to replace the @Model.Strings components in my email template properly. I am using the latest version of .NET Core on a new project. 

Here is my controller code starting the email send off.
```
            Email.DefaultRenderer = new RazorRenderer();
            Email.DefaultSender = new SendGridSender("KEY");
            var email = Email
                .From("do-not-reply@company.io", "Company")
                .To(model.Email)
                .Subject("You have been invited to join " + company.Name + "!")
                .UsingTemplateFromFile($"{Directory.GetCurrentDirectory()}/Views/Emails/StandardEmail.cshtml", new {
                    CallbackUrl = callbackUrl,
                    ButtonText = buttonText,
                    Footer = footer,
                    Body = body,
                    Header = header
                });
            await email.SendAsync();
```

Then my email file has several `@Model.Footer` and based on what is seen above. I am not using any other special code in the email file besides the HTML.

The email properly sends as expected, but I receive the email with the `@Model.Footer` text being shown, instead of the data being passed in the model above.

**Comment by mxmissile** [comment]
Are your other properties working? (`ButtonText`, `Body` etc)

**Comment by Failcookie** [comment]
Good question! They are not working. All of them are having the same issue.

**Comment by bjcull** [comment]
Hey @Failcookie Can you please post the template as well? Nothing obvious stands out yet.

**Comment by etherington** [comment]
I'm having the same problem.

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>WelcomeEmail</title>
</head>
<body>
<div>
    <h4>Listee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
         FirstName
        </dt>
        <dd>
            @Model.FirstName
        </dd>
        <dt>
            LastName
        </dt>
        <dd>
            @Model.LastName
        </dd>
        <dt>
            EmailAddress
        </dt>
        <dd>
            @Model.EmailAddress
        </dd>       
    </dl>
</div>
</body>
</html>

**Comment by Piusn** [comment]
Please ensure you adding this line of code

// Using Razor templating package
Email.DefaultRenderer = new RazorRenderer();

At your start up. This should work
