### ISSUE TITLE
How do I disable encoding?

### ISSUE THREAD

**Issue by mxmissile** [lukencode/FluentEmail#78]
I'm using the `UsingTemplateFromFile(`) and a simple string property `@Model.Body`, however my body has html. Its currently encoding the output. I cannot use `@Html.Raw()` because its not available in RazorLight. My string is not encoded when passing to the `UsingTemplateFromFile` method. How do I force this to not encode my output?

**Comment by mxmissile** [comment]
This hackity hack worked, wish there was an alternative or maybe I'm missing something...

`@(new HtmlString(Model.Body))`

**Comment by bjcull** [comment]
Apparently @Raw("Enter your text here") should work. Found via this https://github.com/toddams/RazorLight/issues/22

Can you give it a go and let me know?

**Comment by mxmissile** [comment]
That worked, thanks @bjcull.
