### ISSUE TITLE
New Email Class constructor that will convert/import a System.Net.Mail.MailMessage

### ISSUE THREAD

**Issue by tgourley** [lukencode/FluentEmail#84]
Any thoughts of adding a new constructor that will take in a MailMessage object and convert that into a FluentEmail Email object?  I am playing around with FluentEmail and just thinking of ways that could make it easier to convert from an SMTP setup to FluentEmail?

**Comment by lukencode** [comment]
Hi @tgourley I think that type of code would be better as a project specific utility function rather than a core constructor.
