### ISSUE TITLE
Support for Reply-To when using mailgun

### ISSUE THREAD

**Issue by svrooij** [lukencode/FluentEmail#93]
According to [sending with the api](https://documentation.mailgun.com/en/latest/api-sending.html#sending) you need to set a specific parameter to send the correct `Reply-To` value.

I think something like this should be added to [MailgunSender.cs](https://github.com/lukencode/FluentEmail/blob/master/src/Senders/FluentEmail.Mailgun/MailgunSender.cs):
```csharp
email.Data.ReplyToAddresses.ForEach(x => {
                parameters.Add(new KeyValuePair<string, string>("h:Reply-To", $"{x.Name} <{x.EmailAddress}>"));
            });
```

Do you want me to create a PR for this?

**Comment by lukencode** [comment]
Hi @svrooij looks like you know what needs doing. If you create a pull request I can merge it in.

**Comment by svrooij** [comment]
There you go!

**Comment by svrooij** [comment]
I see you haven't implemented automatic building/publishing to nuget. So you got any idea on when it will be available there?

**Comment by bjcull** [comment]
Pushed 2.4.1 just now, give it time to hit the index.
